---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Restart service on first node
  service:
    name: "{{ keystone_system_service_name }}"
    state: restarted
    pattern: "{{ keystone_system_service_name }}"
  register: _restart
  until: _restart|success
  retries: 5
  delay: 2
  when:
    - inventory_hostname == groups['keystone_all'][0]
    - (keystone_apache_enabled | bool) or (keystone_mod_wsgi_enabled | bool)
  notify:
    - Wait for keystone service port

- name: Restart Nginx on first node
  service:
    name: nginx
    state: restarted
  register: keystone_restart
  until: keystone_restart | success
  retries: 5
  delay: 2
  when:
    - inventory_hostname == groups['keystone_all'][0]
    - not keystone_apache_enabled | bool

- name: Restart Keystone APIs on first node
  service:
    name: "{{ item }}"
    state: "restarted"
  register: keystone_restart
  until: keystone_restart | success
  retries: 5
  delay: 2
  with_items: "{{ keystone_wsgi_program_names }}"
  when:
    - inventory_hostname == groups['keystone_all'][0]
    - not keystone_mod_wsgi_enabled | bool
  notify:
    - Wait for keystone service port

- name: Wait for keystone service port
  wait_for:
    port: "{{ keystone_service_port }}"
    timeout: 25
    delay: 10
  register: keystone_wait_check
  until: keystone_wait_check | success
  retries: 5

- name: Restart service on other nodes
  service:
    name: "{{ keystone_system_service_name }}"
    state: restarted
    pattern: "{{ keystone_system_service_name }}"
  register: _restart
  until: _restart|success
  retries: 5
  delay: 2
  when:
    - inventory_hostname != groups['keystone_all'][0]
    - (keystone_apache_enabled | bool) or (keystone_mod_wsgi_enabled | bool)

- name: Restart Nginx on other nodes
  service:
    name: nginx
    state: restarted
  register: keystone_restart
  until: keystone_restart | success
  retries: 5
  delay: 2
  when:
    - inventory_hostname != groups['keystone_all'][0]
    - not keystone_apache_enabled | bool

- name: Restart Keystone APIs on other nodes
  service:
    name: "{{ item }}"
    state: "restarted"
  register: keystone_restart
  until: keystone_restart | success
  retries: 5
  delay: 2
  with_items: "{{ keystone_wsgi_program_names }}"
  when:
    - inventory_hostname != groups['keystone_all'][0]
    - not keystone_mod_wsgi_enabled | bool

- name: Restart Shibd
  service:
    name: "shibd"
    state: "restarted"
    pattern: "shibd"
  register: shibd_restart
  until: shibd_restart|success
  retries: 5
  delay: 2

- name: Perform a Keystone DB sync contract
  command: "{{ keystone_bin }}/keystone-manage db_sync --contract"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
